version: '1.0'

services:
  station:
    image:
    ports:
      - "8008:8008"
    volumes:
      - ./Station:/Station
    command:
      - bash
      - -c
      - |
        python manage.py migrate  # 执行数据库迁移
        python manage.py runserver 0.0.0.0:8008
    depends_on:
      - db

  frontend-vue:
    image: station_frontend:1.0
    ports:
      - "8080:8080"
    volumes:
      - ./FrontEnd:/app/
    command: "npm run dev"

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "zyc010804"
      MYSQL_DATABASE: "station"
    ports:
      - "3306:3306"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro